In [9]:
import pandas as pd

In [10]:
data = {
'X': [1, 2, 3, 4, 5, 7, 10],
'Y': [2, 3, 5, 4, 6, 6, 8]
}

In [11]:
data

{'X': [1, 2, 3, 4, 5, 7, 10], 'Y': [2, 3, 5, 4, 6, 6, 8]}

In [12]:
df = pd.DataFrame(data)
df.head()

   X  Y
0  1  2
1  2  3
2  3  5
3  4  4
4  5  6

# Calculate Pearson correlation

In [13]:
pearson_corr = df['X'].corr(df['Y'])
print("Pearson correlation coefficient:", pearson_corr)

Pearson correlation coefficient: 0.9391480052471199

In [14]:
df.corr()

          X         Y
X  1.000000  0.939148
Y  0.939148  1.000000